package:
  name: conda-rlock
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  git_url: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - maturin
  run:
    - python >=3.9,<4.0.0
    - conda >=23.9.0

test:
  imports:
    - conda_rlock_plugin
    - conda_rlock_plugin.conda_rlock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/travishathaway/conda-rlock
  summary: A plugin providing lock file capability for conda
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - travishathaway
