context:
  name: conda-rlock
  version: "0.1.0"

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/travishathaway/conda-rlock

build:
  number: 0

outputs:
  - package:
      name: conda-rlock
    build:
      # only build for the minimal python version
      script: build_base
      python:
        version_independent: true
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - maturin >=1.2.2,<2
        - ${{ compiler('rust') }}
        - cargo-bundle-licenses
        - conda
      host:
        - conda
        - python
        - maturin >=1.2.2,<2
        - pip
        - if: unix
          then:
            - openssl
      run:
        - python >=3.9
        - conda >=24.11.0
        - click
      ignore_run_exports:
        from_package:
          - cross-python_${{ target_platform }}
    tests:
      - python:
          imports:
            - conda_rlock_plugin
          python_version: ["${{ python_min ~ '.*' }}", "3.12.*"]
