source:
  - git: https://github.com/travishathaway/conda-rlock

package:
  name: conda-rlock
  version: 0.1.0

build:
  script: build_base
requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.2.2,<2
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1.2.2,<2
  run:
    - conda >=24.11.0
    - click
    - python =${{python}}
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}
tests:
  - python:
      imports:
        - conda_rlock_plugin
        - conda_rlock_plugin.conda_rlock
