[project]
authors = ["Travis Hathaway <travis.j.hathaway@gmail.com>"]
channels = ["conda-forge"]
description = "Create lock files in conda with rattler_lock"
name = "conda-rlock"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
check = "cargo check"

[dependencies]
conda = ">=24.11.3"

[environments]
test = { features = ["build", "test"], solve-group = "default" }
build = ["build"]

[feature.build.dependencies]
conda-build = ">=24.11.1"
maturin = "~=1.2.2"
pip = "~=23.2.1"
rust = "~=1.85.0"
anaconda-client = "*"

[feature.build.tasks]
build = "PIP_REQUIRE_VIRTUALENV=false maturin develop"
build-release = "PIP_REQUIRE_VIRTUALENV=false maturin develop --release"

[feature.test.dependencies]
python = "3.9.*"

ruff = ">=0.3.3,<0.4"
mypy = "~=1.5.1"

pytest = "~=7.4.0"
pytest-asyncio = "0.21.1.*"
pytest-xprocess = ">=0.23.0,<0.24"
syrupy = ">=4.8.2"
typos = ">=1.23.1,<2"

pre-commit = ">=3.7.1,<4"
pre-commit-hooks = ">=4.6.0,<5"

[feature.test.tasks]
test = { cmd = "pytest --doctest-modules", depends-on = ["build"] }
fmt-python = "ruff format rattler examples tests"
fmt-rust = "cargo fmt --all"
lint-python = "ruff check ."
lint-rust = "cargo clippy --all"
fmt = { depends-on = ["fmt-python", "fmt-rust"] }
lint = { depends-on = ["type-check", "lint-python", "lint-rust"] }
type-check = { cmd = "mypy", depends-on = ["build"] }
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run"
