name: Release to channel

on:
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-20.04 }
          - { target: win-64, os: windows-latest }
          # force older macos-13 to get x86_64 runners
          - { target: osx-64, os: macos-13 }
          - { target: osx-arm64, os: macos-14 }
      fail-fast: false

    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.0
          environment: build

      - name: Add .pixi/envs/build/bin to the $PATH
        shell: bash
        run: |
          echo "$(pwd)/.pixi/envs/build/bin" >> $GITHUB_PATH

      - name: Run code in changed subdirectories
        shell: bash
        run: |
          rattler-build build --recipe-dir recipe \
            --skip-existing=all --target-platform=${{ matrix.target }} \
            -c conda-forge

      - name: Upload all packages
        shell: bash
        run: |
          export ANACONDA_API_KEY=${{ secrets.ANACONDA_ORG_TOKEN }}
          for file in output/**/*.conda; do
            rattler-build upload anaconda -o thath --force "$file"
          done
